/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import DAO.AccountDAO;
import java.awt.Color;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.List;
import java.util.Vector;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.SwingUtilities;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import model.Account;
import model.Role;

/**
 *
 * @author BinDz
 */
public class ManageAccount extends javax.swing.JPanel {

    DefaultTableModel dtf;
    Account account;
    List<Account> listacc;
    List<Role> lr;
    Account acclogin;

    /**
     * Creates new form NewJPanel
     */
    public ManageAccount(Account acclogin) {
        initComponents();
        load_data();
        this.acclogin = acclogin;

    }

    private void load_data() {
        AccountDAO ad = new AccountDAO();
        listacc = ad.getAllAccount1();
        String columns[] = {"STT", "Tên", "Số điện thoại", "Email", "Address", "Ngày sinh", "Chức vụ", "Trạng thái"};
        DefaultTableModel dtm = new DefaultTableModel(columns, 0);
        Integer i = 1;
        for (Account a : listacc) {
            LocalDate dt = LocalDate.parse(a.getBirthday());
            DateTimeFormatter dtf = DateTimeFormatter.ofPattern("dd-MM-yyyy");
            String time = dtf.format(dt);

            dtm.addRow(new Object[]{i, a.getName(), a.getPhone(), a.getEmail(), a.getAddress(), time, a.getRolde_Name(), a.getStatus() == 0 ? "Đang giảng dạy" : "Đã nghỉ"});
            i++;
        }
        tbAccount.setModel(dtm);
        tbAccount.setRowHeight(25);
        if (listacc.size() > 0) {
            tbAccount.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
                @Override
                public void valueChanged(ListSelectionEvent lse) {
                    int pos = tbAccount.getSelectedRow();
                    if (pos < 0) {
                        pos = 0;
                    }

                    account = listacc.get(pos);
                }
            });
        }
    }

    void load_find(String name) {
        AccountDAO ad = new AccountDAO();
        listacc = ad.findAccount(name);
        String columns[] = {"STT", "Tên", "Số điện thoại", "Email", "Address", "Ngày sinh", "Chức vụ", "Trạng thái"};
        DefaultTableModel dtm = new DefaultTableModel(columns, 0);
        Integer i = 1;
        for (Account a : listacc) {
            LocalDate dt = LocalDate.parse(a.getBirthday());
            DateTimeFormatter dtf = DateTimeFormatter.ofPattern("dd-MM-yyyy");
            String time = dtf.format(dt);

            dtm.addRow(new Object[]{i, a.getName(), a.getPhone(), a.getEmail(), a.getAddress(), time, a.getRolde_Name(), a.getStatus() == 0 ? "Đang giảng dạy" : "Đã nghỉ"});
            i++;
        }
        tbAccount.setModel(dtm);
        tbAccount.setRowHeight(25);
        if (listacc.size() > 0) {
            tbAccount.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
                @Override
                public void valueChanged(ListSelectionEvent lse) {
                    int pos = tbAccount.getSelectedRow();
                    if (pos < 0) {
                        pos = 0;
                    }

                    account = listacc.get(pos);
                }
            });
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        rSButtonMetro5 = new rojerusan.RSButtonMetro();
        rSButtonMetro6 = new rojerusan.RSButtonMetro();
        rSButtonMetro7 = new rojerusan.RSButtonMetro();
        rSButtonMetro8 = new rojerusan.RSButtonMetro();
        jPanel9 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        rSButtonMetro9 = new rojerusan.RSButtonMetro();
        jPanel10 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbAccount = new javax.swing.JTable();

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rSButtonMetro5.setBackground(new java.awt.Color(255, 255, 255));
        rSButtonMetro5.setForeground(new java.awt.Color(0, 0, 0));
        rSButtonMetro5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_update_50px.png"))); // NOI18N
        rSButtonMetro5.setText("Sửa");
        rSButtonMetro5.setBorderPainted(false);
        rSButtonMetro5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        rSButtonMetro5.setPreferredSize(new java.awt.Dimension(100, 100));
        rSButtonMetro5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        rSButtonMetro5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                rSButtonMetro5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                rSButtonMetro5MouseExited(evt);
            }
        });
        rSButtonMetro5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMetro5ActionPerformed(evt);
            }
        });
        jPanel8.add(rSButtonMetro5, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 10, 70, 70));

        rSButtonMetro6.setBackground(new java.awt.Color(255, 255, 255));
        rSButtonMetro6.setForeground(new java.awt.Color(0, 0, 0));
        rSButtonMetro6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_refresh_50px.png"))); // NOI18N
        rSButtonMetro6.setText("Refresh");
        rSButtonMetro6.setBorderPainted(false);
        rSButtonMetro6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        rSButtonMetro6.setPreferredSize(new java.awt.Dimension(100, 100));
        rSButtonMetro6.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        rSButtonMetro6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                rSButtonMetro6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                rSButtonMetro6MouseExited(evt);
            }
        });
        rSButtonMetro6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMetro6ActionPerformed(evt);
            }
        });
        jPanel8.add(rSButtonMetro6, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 10, 70, 70));

        rSButtonMetro7.setBackground(new java.awt.Color(255, 255, 255));
        rSButtonMetro7.setForeground(new java.awt.Color(0, 0, 0));
        rSButtonMetro7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_delete_bin_50px.png"))); // NOI18N
        rSButtonMetro7.setText("Xoá");
        rSButtonMetro7.setBorderPainted(false);
        rSButtonMetro7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        rSButtonMetro7.setPreferredSize(new java.awt.Dimension(100, 100));
        rSButtonMetro7.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        rSButtonMetro7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                rSButtonMetro7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                rSButtonMetro7MouseExited(evt);
            }
        });
        rSButtonMetro7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMetro7ActionPerformed(evt);
            }
        });
        jPanel8.add(rSButtonMetro7, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 10, 70, 70));

        rSButtonMetro8.setBackground(new java.awt.Color(255, 255, 255));
        rSButtonMetro8.setForeground(new java.awt.Color(0, 0, 0));
        rSButtonMetro8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_ball_point_pen_50px.png"))); // NOI18N
        rSButtonMetro8.setText("Thêm");
        rSButtonMetro8.setBorderPainted(false);
        rSButtonMetro8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        rSButtonMetro8.setPreferredSize(new java.awt.Dimension(100, 100));
        rSButtonMetro8.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        rSButtonMetro8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                rSButtonMetro8MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                rSButtonMetro8MouseExited(evt);
            }
        });
        rSButtonMetro8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMetro8ActionPerformed(evt);
            }
        });
        jPanel8.add(rSButtonMetro8, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, 70, 70));

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_content_50px.png"))); // NOI18N
        jLabel6.setText("Quản lý tài khoản");
        jPanel9.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1, 240, 110));

        jPanel8.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 2, 260, 110));

        rSButtonMetro9.setBackground(new java.awt.Color(255, 255, 255));
        rSButtonMetro9.setForeground(new java.awt.Color(0, 0, 0));
        rSButtonMetro9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_search_more_50px_1.png"))); // NOI18N
        rSButtonMetro9.setText("Tìm kiếm");
        rSButtonMetro9.setBorderPainted(false);
        rSButtonMetro9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        rSButtonMetro9.setPreferredSize(new java.awt.Dimension(100, 100));
        rSButtonMetro9.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        rSButtonMetro9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                rSButtonMetro9MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                rSButtonMetro9MouseExited(evt);
            }
        });
        rSButtonMetro9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSButtonMetro9ActionPerformed(evt);
            }
        });
        jPanel8.add(rSButtonMetro9, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 10, 80, 70));

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));

        tbAccount.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbAccount.setGridColor(new java.awt.Color(0, 0, 0));
        tbAccount.setSelectionBackground(new java.awt.Color(51, 204, 255));
        jScrollPane1.setViewportView(tbAccount);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 820, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 820, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 820, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 568, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(118, 118, 118)
                            .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void rSButtonMetro5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rSButtonMetro5MouseEntered
        rSButtonMetro5.setBackground(new Color(85, 159, 213));
    }//GEN-LAST:event_rSButtonMetro5MouseEntered

    private void rSButtonMetro5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rSButtonMetro5MouseExited
        rSButtonMetro5.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_rSButtonMetro5MouseExited

    private void rSButtonMetro6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rSButtonMetro6MouseEntered
        rSButtonMetro6.setBackground(new Color(85, 159, 213));
    }//GEN-LAST:event_rSButtonMetro6MouseEntered

    private void rSButtonMetro6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rSButtonMetro6MouseExited
        rSButtonMetro6.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_rSButtonMetro6MouseExited

    private void rSButtonMetro7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rSButtonMetro7MouseEntered
        rSButtonMetro7.setBackground(new Color(85, 159, 213));
    }//GEN-LAST:event_rSButtonMetro7MouseEntered

    private void rSButtonMetro7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rSButtonMetro7MouseExited
        rSButtonMetro7.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_rSButtonMetro7MouseExited

    private void rSButtonMetro8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rSButtonMetro8MouseEntered
        rSButtonMetro8.setBackground(new Color(85, 159, 213));
    }//GEN-LAST:event_rSButtonMetro8MouseEntered

    private void rSButtonMetro8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rSButtonMetro8MouseExited
        rSButtonMetro8.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_rSButtonMetro8MouseExited

    private void rSButtonMetro8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMetro8ActionPerformed
        if (acclogin.getId() == 1) {
            JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(this);
            FrmDiaglogAccount facc = new FrmDiaglogAccount(frame, true, null);
            facc.setLocationRelativeTo(this);
            facc.setVisible(true);
            load_data();
        } else {
            MessageBox mb = new MessageBox(null, true, "<html><pre>Bạn không có quyền \n truy cập</pre></html>");
            mb.setLocationRelativeTo(this);
            mb.setVisible(true);
        }


    }//GEN-LAST:event_rSButtonMetro8ActionPerformed

    private void rSButtonMetro7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMetro7ActionPerformed
        if (acclogin.getId() == 1) {
            int pos = tbAccount.getSelectedRow();
            if (pos < 0) {
                JOptionPane.showMessageDialog(null, "Hãy chọn cái cần xoá !");
            }
            int id = listacc.get(pos).getId();
            String name = listacc.get(pos).getName();
            AccountDAO ad = new AccountDAO();
            int choose = JOptionPane.showConfirmDialog(null, "Bạn chắc chắn muốn xoá " + name + " chứ!", "Xoá " + name, JOptionPane.YES_NO_OPTION);

            if (choose == JOptionPane.YES_OPTION) {
                ad.delete(id);
                JOptionPane.showMessageDialog(null, "Đã xoá " + name);
                load_data();
            }
        } else {
            MessageBox mb = new MessageBox(null, true, "<html><pre>Bạn không có quyền \n truy cập</pre></html>");
            mb.setLocationRelativeTo(this);
            mb.setVisible(true);
        }

    }//GEN-LAST:event_rSButtonMetro7ActionPerformed

    private void rSButtonMetro9MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rSButtonMetro9MouseEntered
        rSButtonMetro9.setBackground(new Color(85, 159, 213));
    }//GEN-LAST:event_rSButtonMetro9MouseEntered

    private void rSButtonMetro9MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rSButtonMetro9MouseExited
        rSButtonMetro9.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_rSButtonMetro9MouseExited

    private void rSButtonMetro6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMetro6ActionPerformed
        load_data();
    }//GEN-LAST:event_rSButtonMetro6ActionPerformed

    private void rSButtonMetro5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMetro5ActionPerformed
        if (acclogin.getId() == 1) {
            if (account != null) {
                JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(this);
                FrmDiaglogAccount facc = new FrmDiaglogAccount(frame, true, account);
                facc.setLocationRelativeTo(this);
                facc.setVisible(true);
                load_data();
            } else {
                JOptionPane.showMessageDialog(null, "Bạn chưa chọn !");
            }
        } else {
            MessageBox mb = new MessageBox(null, true, "<html><pre>Bạn không có quyền \n truy cập</pre></html>");
            mb.setLocationRelativeTo(this);
            mb.setVisible(true);
        }


    }//GEN-LAST:event_rSButtonMetro5ActionPerformed

    private void rSButtonMetro9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSButtonMetro9ActionPerformed
        JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(this);
        FrmFind ff = new FrmFind(frame, true);
        ff.setLocationRelativeTo(this);
        ff.setVisible(true);
        String a = ff.getData();
        load_find(a);


    }//GEN-LAST:event_rSButtonMetro9ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private rojerusan.RSButtonMetro rSButtonMetro5;
    private rojerusan.RSButtonMetro rSButtonMetro6;
    private rojerusan.RSButtonMetro rSButtonMetro7;
    private rojerusan.RSButtonMetro rSButtonMetro8;
    private rojerusan.RSButtonMetro rSButtonMetro9;
    private javax.swing.JTable tbAccount;
    // End of variables declaration//GEN-END:variables
}
